version: '3'

networks:
  randomnetworkname:

services:
  apache:
    build: .
    container_name: php
    restart: always
    ports:
      - '8080:80'
    networks:
      - randomnetworkname
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysqldb
    links:
      - mysqldb

  mysqldb:
    container_name: db
    image: mysql:5.7
    restart: always
    ports:
      - '3307:3306'
    networks:
      - randomnetworkname
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=products 
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080
    networks:
      - randomnetworkname
      

    
 

